openhab/org.openhab.ui.habpanel

- web/app/widgets/chart/chart.widget.js
> Fix persistence API URL for charts

- web/app/widgets/knob/knob.widget.js
- web/app/widgets/slider/slider.widget.js
> Better handling of decimal values in slider & knob

- web/app/services/openhab.service.js
- web/app/widgets/chart/chart.tpl.html
- web/app/widgets/chart/chart.widget.js
> Allow groups in regular/rrd4j charts (#15)

- web/app/dashboard/dashboard.edit.controller.js
- web/app/dashboard/dashboard.edit.html
- web/app/dashboard/dashboard.view.controller.js
- web/app/menu/menu.controller.js
- web/app/menu/menu.html
- web/app/menu/menu.settings.tpl.html
- web/app/services/openhab.service.js
- web/app/services/persistence.service.js
- web/assets/style.css
Part 1 of the main menu massive feature upgrade...!
> Main menu improvements

- web/app/widgets/knob/knob.settings.tpl.html
- web/app/widgets/slider/slider.settings.tpl.html
> Fix #30: allow decimal bounds (knob & slider)

- web/app/menu/menu.settings.tpl.html
- web/app/services/openhab.service.js
- web/app/widgets/button/button.settings.tpl.html
- web/app/widgets/button/button.widget.js
- web/app/widgets/chart/chart.settings.tpl.html
- web/app/widgets/colorpicker/colorpicker.settings.tpl.html
- web/app/widgets/dummy/dummy.settings.tpl.html
- web/app/widgets/dummy/dummy.widget.js
- web/app/widgets/frame/frame.widget.js
- web/app/widgets/image/image.settings.tpl.html
- web/app/widgets/image/image.widget.js
- web/app/widgets/knob/knob.settings.tpl.html
- web/app/widgets/knob/knob.widget.js
- web/app/widgets/label/label.widget.js
- web/app/widgets/slider/slider.settings.tpl.html
- web/app/widgets/slider/slider.widget.js
- web/app/widgets/switch/switch.settings.tpl.html
- web/app/widgets/switch/switch.widget.js
> Fix remaining instances of 'OpenHAB' to 'openHAB'

- web/app/services/speech.service.js
- web/index.html
> Safer dereferencing for service worker, TTS voices

- web/app/services/openhab.service.js
Saw [this](https://github.com/eclipse/smarthome/pull/2314) by accident :)
I'm in too! :)
> Handle SSE audio events

- web/app/services/openhab.service.js
> Fix SSE audio event payload parsing

- web/app/widgets/chart/chart.settings.tpl.html
- web/app/widgets/chart/chart.widget.js
Support multiple series with individual options, axis configuration (incl. secondary).
ATTENTION: this breaks current interactive charts, you'll have to reconfigure them.
Image charts are unchanged.
Closes #62.
> Advanced settings for interactive charts

- web/app/services/openhab.service.js
> SSE: React to ItemStateChangedEvent

- web/app/widgets/chart/chart.settings.tpl.html
- web/app/widgets/chart/chart.widget.js
- Typo in primary axis includezero option
- Fix #83
- Merged Live-Update tab into Series
> Interactive charts fixes

- web/app/widgets/image/image.settings.tpl.html
- web/app/widgets/image/image.tpl.html
- web/app/widgets/image/image.widget.js
> Auto-refresh feature for image widget

- web/app/widgets/image/image.widget.js
Changed to a better implementation by @andreasgebauer (#87).
Closes #87.
Also-by: Andreas Gebauer <an.ge.ber.81@gmail.com> (github: andreasgebauer)
> Image autorefresh: $interval instead of $timeout

- web/app/menu/menu.html
> No drag on main menu tiles when editing

- web/app/widgets/button/button.settings.tpl.html
> Add missing class to button settings

- web/app/widgets/frame/frame.settings.tpl.html
- web/app/widgets/frame/frame.widget.js
IFrame widget with dynamic URLs support (resolves #98)
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>
> iFrame widget with Item support

- web/app/widgets/chart/chart.widget.js
> Fix #107 - inline functions in chart controller

- web/app/settings/settings.controller.js
> Fix #112 - save additional settings w/ new panel config

- web/app/services/openhab.service.js
Sorry, I had missed that in https://github.com/openhab/org.openhab.ui.habpanel/pull/123.
Signed-off-by: Kai Kreuzer <kai@openhab.org>
> also adapted config id in the javascript code

- web/app/widgets/chart/chart.widget.js
> Chart: Don't initialize secondary axis if not enabled

- web/app/settings/settings.widgets.list.controller.js
- web/app/settings/settings.widgets.list.html
- web/app/widgets/template/template.settings.tpl.html
- web/app/widgets/template/template.widget.js
> File import event handlers broken because of CSP

- web/app/services/openhab.service.js
> Update groups states when receiving GroupItemStateChanged events

- web/app/settings/settings.widgets.designer.controller.js
- web/app/widgets/template/template.widget.js
Returns all item data to the UI. This is useful for dynamically
generating HTML selects and other forms of dropdown menus:
Example habpanel Template:
```
<h4>Basement Hub</h4>
{{itemname = 'harmonyhub_hub_Basement_currentActivity';""}}
<div class="btn-group" uib-dropdown>
<button id="single-button" type="button" class="btn btn-primary" uib-dropdown-toggle>
{{itemValue(itemname)}} <span class="caret"></span>
</button>
<ul class="dropdown-menu" uib-dropdown-menu role="menu" aria-labelledby="single-button">
<li role="menuitem" ng-repeat="option in itemGet(itemname).stateDescription.options">
<a ng-click="sendCmd(itemname, option.label);">{{option.label}}</a>
</li>
</ul>
</div>
```
> Template functions: add getItem, rename itemValue to itemState

- web/app/widgets/image/image.settings.tpl.html
- web/app/widgets/image/image.widget.js
Related to #19 
According to [the docs](http://docs.openhab.org/configuration/sitemaps.html#element-type-image) Image can source already from String item. If it's sourcing from `url` attribute, then it's not exposed in the items (it's a sitemap-oriented element).
I welcome any comments! 🙂 
Signed-off-by: Kuba Wolanin <hi@kubawolanin.com>
> Image widget sourcing from String item

- web/app/widgets/knob/knob.settings.tpl.html
- web/app/widgets/knob/knob.widget.js
> Add a few missing options to the Knob widget

- web/app/menu/drawer.tpl.html
- web/app/settings/settings.html
Replaces 'HABPanel' in the side drawer header when set.
> Panel name setting

- README.md
> Switch to hash for heading level 1

- web/app/widgets/chart/chart.widget.js
> Fix #140 - month name on first day only at midnight

- web/app/settings/settings.widgets.designer.html
> Wrong tip for icon config setting in widget designer

- web/app/dashboard/dashboard.edit.html
- web/app/services/openhab.service.js
- web/app/settings/settings.widgets.list.controller.js
- web/app/settings/settings.widgets.list.html
- web/app/widgets/button/button.widget.js
- web/app/widgets/chart/chart.widget.js
- web/app/widgets/clock/clock.widget.js
- web/app/widgets/colorpicker/colorpicker.widget.js
- web/app/widgets/dummy/dummy.widget.js
- web/app/widgets/frame/frame.widget.js
- web/app/widgets/image/image.widget.js
- web/app/widgets/knob/knob.widget.js
- web/app/widgets/label/label.widget.js
- web/app/widgets/slider/slider.widget.js
- web/app/widgets/switch/switch.widget.js
- web/app/widgets/template/template.widget.js
- web/app/widgets/timeline/timeline.widget.js
Implements #164.
Add icons to the "Add widget" menu.
> Add globally provisioned widgets from configuration

- web/app/widgets/colorpicker/colorpicker.tpl.html
- web/app/widgets/timeline/timeline.tpl.html
> Timeline & aCKolor color picker widget titles

- web/app/widgets/colorpicker/colorpicker.widget.js
> Fix #169 - Color picker: handle NULL values

- web/index.html
Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill
> Fix #153 - `Function.prototype.bind()` polyfill

- web/app/widgets/chart/chart.tpl.html
Reported in https://community.openhab.org/t/habpanel-debug-entries-illegal-argument-in-chart-to-log-when-chart-is-selected/27991
> Chart: fix invalid image loads

- web/app/widgets/timeline/timeline.widget.js
Inspired by: https://bl.ocks.org/mbostock/4149176 - thanks!
> Fix #193 - Timeline: auto scale tick format

- web/app/widgets/timeline/timeline.widget.js
> Timeline: fill last partition & better tick format for 2M/4M periods

- web/app/widgets/image/image.settings.tpl.html
- web/app/widgets/image/image.widget.js
> Close #182 - image widget: accept image items

- web/app/widgets/timeline/timeline.widget.js
> Close #191 - timeline: refresh automatically

- web/app/widgets/frame/frame.settings.tpl.html
- web/app/widgets/frame/frame.tpl.html
- web/app/widgets/frame/frame.widget.js
> Close #192 - frame widget: refresh option

- web/app/widgets/knob/knob.settings.tpl.html
- web/app/widgets/knob/knob.widget.js
> knob: fix #211 - options initialization

- web/app/menu/drawer.tpl.html
> Don't wrap long dates in drawer

- web/app/dashboard/dashboard.view.html
- web/app/widgets/slider/slider.widget.js
Regression introduced and reported in #214.
(+ remove leftover in custom header markup)
> Display slider even if it has an invalid value

- web/app/widgets/selection/selection.widget.js
> Selection: Display label of selected choice if provided

- web/app/widgets/frame/frame.widget.js
> Frame widget: fix for query strings

- web/app/widgets/frame/frame.settings.tpl.html
- web/app/widgets/frame/frame.tpl.html
- web/app/widgets/frame/frame.widget.js
- web/app/widgets/image/image.settings.tpl.html
- web/app/widgets/image/image.tpl.html
- web/app/widgets/image/image.widget.js
Hopefully fix #223 this time.
Closes #230.
> Image/frame: autorefresh fixes, optional cache busting

- web/app/widgets/frame/frame.tpl.html
- web/app/widgets/image/image.tpl.html
> Fix #246 - image/frame: no flickering when cache busting on

- web/app/widgets/template/template.widget.js
> Fix #244 - template: refresh upon modal rendered

- web/app/widgets/knob/knob.settings.tpl.html
- web/app/widgets/knob/knob.widget.js
> knob: fix range settings and default text color

- web/app/menu/menu.controller.js
Fixes #262
Signed-off-by: Lucky Mallari <luckymallari@gmail.com>
> Prompt user to confirm dashboard removal

- doc/habpanel.md
Signed-off-by: Thomas Dietrich <thomas.dietrich@tu-ilmenau.de> (github: ThomDietrich)
> Add source front matter

- web/app/app.js
- web/app/services/translation.service.js
> i18n: ignore failed translation loadings, no preferred language

- web/app/dashboard/dashboard.edit.html
> Dashboard designer: various fixes for longer translations

- .classpath
- META-INF/MANIFEST.MF
... required by the latest changes in the ESH target platform
Signed-off-by: Kai Kreuzer <kai@openhab.org>
> some small cleanups

- web/app/widgets/knob/knob.settings.tpl.html
- web/app/widgets/knob/knob.widget.js
> Close #306 - knob: Formatting options for value display

- web/app/widgets/button/button.tpl.html
- web/app/widgets/colorpicker/colorpicker.tpl.html
- web/app/widgets/dummy/dummy.tpl.html
- web/app/widgets/selection/selection.tpl.html
- web/app/widgets/timeline/timeline.tpl.html
> Fix #300 - hide empty labels

- web/app/widgets/selection/selection.widget.js
> Use strict comparator for current selection widget choice

- web/app/widgets/button/button.tpl.html
> Button widget icon follows underlying item state

- web/app/widgets/chart/chart.widget.js
Also apply the computed value to the datapoint state.
> Bugfix for translation of ON / OFF values to numbers
