openhab/org.openhab.ui.habpanel

app/widgets/frame/frame.settings.tpl.html, app/widgets/frame/frame.tpl.html, app/widgets/frame/frame.widget.js, assets/style.css, index.html, vendor/angular-web-colorpicker.js
A simple iFrame widget.
Results vary depending on the url you want to use e.g. www.bbc.co.uk doesn't work. The usual iFrame cross domain issues still apply, but it is fine when using your own simple pages.
My need was primarily to show the running logs in the dashboard using [js-logtail](https://github.com/ukhas/js-logtail)
I played with getting js-logtail within the webapps folder, but Jetty doesn't like symbolic links and you need to use with js-logtail. But very easy to add using something like lighttpd.
The frameless option allows a full bleed to the edges ignoring the 10px padding. If the HTML file doesn't have a background colour, you can manually set one using the same colour picker you use.
Also added a an option for "transparent" in the colour picker as once you set a colour …
=> Iframe widget

web/app/app.js, web/app/dashboard/dashboard.view.controller.js, web/app/menu/menu.controller.js, web/app/menu/menu.html, web/app/services/openhab.service.js, web/app/services/speech.service.js, web/app/settings/settings.controller.js, web/app/settings/settings.html, web/index.html
- Text-to-speech feature: have the device speak the new
value of a String item when it changes
(depends on device, OS, browser capabilities)
- Server-enabled dashboard switching: have an item's state update trigger
a switch to another dashboard (great with server-side rules)
- Add option to prevent scrolling on tablets (now disabled by default)
- Add option to hide the clock in the main menu
=> New settings: contextual dashboards, speech, misc

web/app/dashboard/dashboard.view.controller.js, web/app/dashboard/dashboard.view.html, web/app/menu/menu.controller.js, web/app/menu/menu.html, web/index.html, web/manifest.json
Add ?kiosk=on to the URL to hide the header in dashboards and the main menu (useful for scenarios where limited navigation is desired).
Amended the web app manifest so adding to home from Chrome goes back to the last dashboard.
=> Kiosk mode

web/app/services/openhab.service.js
Fixes an initialization bug with the custom widget collection when using the OH2 service
=> Fix OH2 service custom widgets initialization bug

ESH-INF/config/config.xml, web/app/app.js, web/app/services/openhab.service.js, web/app/services/persistence.service.js
- New parameter "initialPanelConfig" in the openHAB 2 service
configuration - will be taken into account only if a configuration
with this name exists and none is set yet.
- Reject access to routes when lockEditing is enabled.
Related to #78.
=> Initial panel configuration service parameter

web/app/widgets/button/button.settings.tpl.html, web/app/widgets/button/button.widget.js, web/app/widgets/widgets.module.js
The button widget can now perform the following actions, beside
sending a fixed command to an item:
- toggle the state of an item between 2 values (if the state is
already equal to the primary command, use the alternate);
- navigate to another dashboard.
Closes #22.
=> Additional button widget action types

web/app/dashboard/dashboard.edit.controller.js, web/app/dashboard/dashboard.view.controller.js, web/app/menu/menu.controller.js, web/app/menu/menu.settings.tpl.html
Added 2 options in the Advanced tab of the dashboard settings page:
- number of columns (this allows to control the width and height unit) ;
- margin between widgets.
These options are marked experimental/for experts only for now.
Closes #61.
=> Experimental dashboard options

OSGI-INF/dashboardtile.xml
Just noticed that this was not following the standard procedure.
With this change, it is also possible to add static configuration in conf/services/habpanel.cfg.
Unfortunately, this change is breaking, i.e. existing configurations need to be moved from `userdata/config/org/openhab/ui/habpanel.config` to `userdata/config/org/openhab/habpanel.config` by the users.
But better do the change now, before the release, than after it...
Signed-off-by: Kai Kreuzer <kai@openhab.org>
=> fixed config id

web/index.html
Helps mitigate XSS attacks inside expressions and through lazy
loading of external scripts by templates/custom widgets.
With this CSP policy, only local scripts can be loaded
(provided the browser has support for CSP).
WARNING: the user is still responsible for securing the
openHAB instance properly, especially the REST API endpoints
which modify data (POST /service/org.openhab.habpanel/config in
particular), including custom code, and *never* publish them
unsecured on the Internet.
HABPanel lets the user modify templates, and implicitly trusts
the code in these templates, therefore XSS attacks and arbitrary
code execution is always possible even with the expression sandbox!
See: https://docs.angularjs.org/guide/security
=> Add Content-Security-Policy meta tag

web/app/services/openhab.service.js, web/app/widgets/dummy/dummy.widget.js, web/app/widgets/switch/switch.tpl.html, web/app/widgets/switch/switch.widget.js, web/app/widgets/template/template.widget.js
NOTE: added a new parameter to the itemState function in templates:
itemState(name, ignoreTransform)
ignoreTransform is false by default, meaning the transformed state
will be retrieved; if the raw state is desired, set ignoreTranform
to true.
=> Use and update transformed states in switch/dummy/template

web/app/widgets/template/template.widget.js
Fix for Safari (among others) not accepting them.
As reported in https://community.openhab.org/t/template-widget-missing/29537
Also see https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters#Browser_compatibility
=> Template widget: remove itemState default parameter

web/app/widgets/dummy/dummy.tpl.html, web/app/widgets/dummy/dummy.widget.js
Reported in: https://community.openhab.org/t/mapping-of-item-values-not-correctly-shown-in-habpanel/19518/41
=> Dummy widget: use raw state for icon

web/app/services/icon.service.js
Add options to the icon picker to select custom registered icons
(according to http://docs.openhab.org/configuration/items.html#icons)
or a custom URL, without breaking the existing API.
Custom icons are "state-aware": for example, 'myicon' will display
myicon-on.svg resp. switch-off.svg when the item's state is 'ON' resp. 'OFF'.
Custom URLs includes all image formats supported by the browser:  SVG, PNG, JPEG, GIF etc.
=> Icon picker: allow custom icons or custom URLs

web/app/dashboard/dashboard.edit.controller.js, web/app/dashboard/dashboard.view.controller.js, web/app/menu/menu.controller.js, web/app/menu/menu.settings.tpl.html
You'll find these options in the "advanced" tab of the dashboard settings dialog.
Closes #96.
=> New dashboard experimental options: mobile mode, row height

web/app/settings/settings.widgets.list.controller.js, web/app/settings/settings.widgets.list.html, web/app/settings/settings.widgets.list.import-github.js, web/app/settings/settings.widgets.list.import-github.tpl.html
Adds a dialog in the Custom Widgets screen to easily import widgets from a GitHub repository.
Uses the rate-limited GitHub API in anonymous mode (60 requests per hour).
Takes care of already existing widgets - update them in this case.
Added menu entries to easily update and check the Readme file for widgets imported from GitHub.
Can be reused/extended for other sources (Eclipse IoT Marketplace?).
=> Import widgets from a GitHub repository

web/app/menu/menu.controller.js, web/app/menu/menu.html, web/app/menu/menu.settings.tpl.html
This provides the ability to use a custom widget as a main menu tile, including
setting its config, thus allowing dynamic content on the main menu.
The widgets can be clicked like a normal tile, so no need to handle click events
in the widget's template - in fact, any kind of interactivity is discouraged.
You can use `ngModel.name` in the widget template to retrieve the dashboard label.
Also added the ability to prevent the tile from "brightening up" when clicked.
Removed the $interval for the old clock in the main menu controller.
Closes #34, #108.
=> Experimental feature: custom widgets on main menu

web/app/widgets/widgets.module.js
=> Icons in the item picker

web/app/widgets/chart/chart.tpl.html, web/app/widgets/chart/chart.widget.js, web/app/widgets/colorpicker/colorpicker.tpl.html, web/app/widgets/colorpicker/colorpicker.widget.js, web/app/widgets/slider/slider.tpl.html, web/app/widgets/slider/slider.widget.js, web/app/widgets/template/template.widget.js
- slider: Wait for the first event to display the widget (this hack
seems to fix a long-standing display glitch e.g. when switching dashboards);
- chart: attempt to get rid the the initial data series animations;
- colorpicker: remove the initial "flickering";
- template: send an update event after opening a modal dialog
=> Improve the initial rendering of several widgets

web/app/dashboard/dashboard.view.html, web/app/menu/drawer.tpl.html, web/app/menu/menu.controller.js, web/app/menu/menu.html, web/app/menu/menu.settings.tpl.html
This allows the ability to set and configure a custom widget to display
instead of the default design for the side drawer dashboard menu entry,
and the dashboard header. Limited interactivity is recommended!
=> Experimental: use custom widgets for drawer and headers

web/app/widgets/chart/chart.widget.js, web/assets/styles/themes/default.css, web/assets/styles/themes/madras.css, web/assets/styles/themes/material-dark.css, web/assets/styles/themes/material.css, web/assets/styles/themes/orange-tree.css, web/assets/styles/themes/paleblue.css, web/assets/styles/themes/translucent.css
Take a matching chart theme for the current habpanel theme and send it to the ESH chart servlet.
----
The ESH `DefaultChartProvider` recently got a new feature to support different themes:
https://github.com/eclipse/smarthome/pull/4291
This change adds the `&theme=xxx` parameter to the servlet URL, based on the current habpanel theme.
=> Charts: Send `theme` parameter for `default` charts

web/app/widgets/image/image.scss, web/app/widgets/image/image.settings.tpl.html, web/app/widgets/image/image.tpl.html, web/app/widgets/image/image.widget.js
Made the background color of image widgets configurable (basically to support images with transparency). Therefore I would personally prefer 'transparent' as default background color but I have chosen black for backward compatibility.
...it would also be nice to have the border configurable/optional - maybe another pull request follows :)
=> Make the background color of image widgets configurable

web/app/widgets/chart/chart.settings.tpl.html, web/app/widgets/chart/chart.widget.js
The ESH DefaultChartProvider recently got a new feature to hide the legend:
eclipse/smarthome#4291
---
* Add the Option "Show legend" to the chart settings. Only shown if the "Default" chart is selected.
- "automatic" -> let the chart provider decide (current behaviour: hide if there is only one chart series, show otherwise)
- "always" -> force show
- "never" -> force hide
* Send `legend=true/false` to the chart servlet, if "always" or "never" is choosen. If "automatic" is selected, do not send the paramater, as this triggers the automatic decision.
**Chart settings:**
**Setting `Show legend: Never` results in:**
=> Charts: Add "Show legend" option for "Default" charts

web/app/menu/drawer.controller.js, web/app/menu/drawer.tpl.html, web/app/menu/menu.controller.js, web/app/menu/menu.settings.tpl.html
- Get rid of unnecessary logic;
- Add alert in case of error;
- Fix mIssing hydration of `tile.title_color` property in form;
- Also add experimental option to hide dashboard from side drawer menu (closes #238).
=> Improve dashboard settings saving mechanism

web/app/settings/settings.localconfig.controller.js
=> Close #50 - include all panel config data in local editor

web/app/settings/settings.localconfig.controller.js
This ensures the legacy format is always accepted even if it doesn't come from a imported file (for example, copied to the clipboard by Home Builder).
=> Allow pasting the legacy format in the local panel config editor

web/app/widgets/button/button.settings.tpl.html, web/app/widgets/button/button.tpl.html, web/app/widgets/button/button.widget.js, web/app/widgets/dummy/dummy.settings.tpl.html
Previous conversation:
https://github.com/openhab/org.openhab.ui.habpanel/pull/258#issuecomment-354185262
Here's the changes per suggestions:
* Changed "Navigate to dashboard" to "Navigate"
* Change Icons uitab to Display
* Added ability to navigate to an external URL
* Changed ui-select on dashboard select tag
* Use/mimic Dummy widget for Navigate type
* Added ability to show an item value
Basically if you use "Display" on a "Navigate" action type, you can display the Item name/value just like a regular Dummy widget. Same concept as previous PR: ability to navigate to a URL or a dashboard page. Use self/new tab/new window if preferred.
Demo:
I formatted code based on VS Code settings.
You can see actual changes here:
https://github.com/LuckyMallari/org.openhab.ui.habpanel/commit/d56498237 …
=> [Enhancement] Feature/smarterbutton. Ability to navigate to a URL/Dashboard and mimic a Dummy

web/app/widgets/chart/chart.settings.tpl.html, web/app/widgets/chart/chart.widget.js, web/app/widgets/timeline/timeline.settings.tpl.html, web/app/widgets/timeline/timeline.widget.js
- Accurate calculations of start date for M, 2M, 4M, Y periods (fix #265)
- Add missing 2D period
- Omit serviceId parameter for persistence service if blank (use default)
=> Chart/timeline: Fix date calcs, 2D period, optional serviceId

web/app/services/openhab.service.js
Use the first preferred language configured in the browser if no
language is set for the openHAB's i18nProvider.
=> Use browser language if unset on server

web/app/widgets/slider/slider.widget.js
The value of a slider/dimmer item is naively assumed to be numerical. Many OpenHAB dimmer components are issued ON/OFF commands instead of 0/100. This causes the slider widget to display NaN as the item value, and causes visual artifacts as well (value below the floor).
Add a check for ON/OFF strings, before assuming value is numerical and parsing it as a float.
=> Fix NaN display when dimmer issued ON/OFF command

web/app/services/openhab.service.js
OpenHAB permits custom event types to be defined. These events are passed to HABPanel but are silently dropped. By passing on unused events, downstream components such as Widgets can make use of the data.
Note: This PR emits the events onto a new "topic" in $rootScope. The thinking is that by emitting rather than broadcasting, some noise can be avoided by child scopes (and most uses can get $rootScope by using DI). 
Fixes #314.
Signed-off-by: William Welliver <william@welliver.org> (github: hww3)
=> Pass unused OpenHAB events on for other components to use.

web/app/services/openhab.service.js
Only allow custom events (i.e. those whose topic doesn't start
with "smarthome") to be emitted on the root scope.
This prevents flooding and a potential performance hit for users
who don't need this feature.
Related to #315.
=> Don't forward smarthome events to rootScope

web/app/widgets/selection/selection.widget.js
When the filter function is used with an object expression, it returns all objects whose properties CONTAIN the value of the given object, and not which EQUAL the value, see [0]. So if you e.g. have 3 choices with 15, 1 and 31 as "cmd" property, a "{cmd: 1}" expression returns all 3 objects, and not only the object which actually has "cmd: 1", and the wrong object with "cmd: 15" is displayed because it'the first one.
With this fix a function expression is used for the filter, which finds the choice with the exact matching "cmd" property.
[0] https://docs.angularjs.org/api/ng/filter/filter
=> Fixed display of selected choice in selection widget

web/app/dashboard/dashboard.view.controller.js
=> Fix #339 - fullscreen broken in Chrome 71+
